# Generated by Django 4.0.4 on 2022-05-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_role',
            new_name='Emp_role',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mobile_no',
            new_name='Mobile_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_no',
        ),
    ]
