# Generated by Django 4.0.5 on 2022-06-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('item_cost', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('volume', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
